# Generated by Django 4.1.5 on 2023-03-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Grenade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "side",
                    models.CharField(
                        choices=[("CT", "Ct Side"), ("T", "T Side")], max_length=15
                    ),
                ),
                ("image_example", models.ImageField(upload_to="")),
                (
                    "grenade_type",
                    models.CharField(
                        choices=[
                            ("MOLY", "Moly"),
                            ("SMOKE", "Smoke"),
                            ("FLASH", "Flash"),
                            ("HE", "He"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgcsgrenadebot.map",
                    ),
                ),
            ],
        ),
    ]
