# Generated by Django 4.1.5 on 2023-03-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgcsgrenadebot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grenade",
            name="plant",
            field=models.CharField(
                choices=[("A", "Plant A"), ("B", "Plant B")], max_length=15, null=True
            ),
        ),
    ]
